// This file is generated by scripts/generate-question-manifest.mjs.
// Do not edit it manually.

export const questionSetCounts = {
    '/cloudfront/cloudfront1': 62,
    '/cloudfront/cloudfront2': 55,
    '/dns/dns1': 86,
    '/dns/dns2': 15,
    '/dynamodb/dynamodb1': 14,
    '/dynamodb/dynamodb2': 5,
    '/lambda/lambda1': 116,
    '/lambda/lambda2': 32,
    '/s3/s3_1': 54,
    '/s3/s3_2': 77,
    '/ssa': 20,
} as const

export type QuestionSetPath = keyof typeof questionSetCounts
