// This file is generated by scripts/generate-question-manifest.mjs.
// Do not edit it manually.

export const questionSetCounts = {
    '/aws_service/aws_service1': 99,
    '/aws_service/aws_service2': 120,
    '/cloudfront/cloudfront1': 62,
    '/cloudfront/cloudfront2': 55,
    '/dns/dns1': 86,
    '/dns/dns2': 15,
    '/dynamodb/dynamodb1': 14,
    '/dynamodb/dynamodb2': 5,
    '/lambda/lambda1_1': 42,
    '/lambda/lambda1_2': 38,
    '/lambda/lambda1_3': 36,
    '/lambda/lambda2_1': 32,
    '/lambda/lambda2_2': 32,
    '/lambda/lambda2_3': 31,
    '/lambda/lambda2_4': 40,
    '/s3/s3_1': 54,
    '/s3/s3_2': 77,
    '/ssa': 20,
} as const

export type QuestionSetPath = keyof typeof questionSetCounts
