// This file is generated by scripts/generate-question-manifest.mjs.
// Do not edit it manually.

export const questionSetCounts = {
    '/ssa': 20,
    '/dns/dns1': 86,
    '/dns/dns2': 15,
    '/cloudfront/cloudfront1': 62,
    '/cloudfront/cloudfront2': 55,
    '/dynamodb/dynamodb1': 14,
    '/dynamodb/dynamodb2': 5,
} as const

export type QuestionSetPath = keyof typeof questionSetCounts
